import { lin_fae_factura_enc } from './../../../app/features/invoice/components/model/lin_fae_factura_enc';

{
    "Invoices":[
       {
          "FAE_CODDPT":"LIN  ",
          "FAE_CLAVE":"FEXP",
          "FAE_SERIE":"19DS000X",
          "FAE_CODTDD":"70",
          "FAE_CODEMP":"001  ",
          "FAE_CODCGR":"001  ",
          "FAE_CORRELATIVO":463,
          "FAE_CODSUC":"01   ",
          "FAE_CODCLI":28,
          "FAE_ID":25540,
          "FAE_CLIENTE_NOMBRE":"SWISSTEX EL SALVADOR",
          "FAE_CLIENTE_REGISTRO":"",
          "FAE_CLIENTE_GIRO":"",
          "FAE_CLIENTE_DIRECCION":"KM. 26 CARR. STA. ANA, COMPLEJO INDUSTRIAL INTERCOMPLEX, LOTE 2C",
          "FAE_CLIENTE_NUMERO_CONTRIBUYENTE":"",
          "FAE_FECHA":"2022-03-25T00:00:00",
          "FAE_DESNVL":"LISTA 2017",
          "FAE_ANULADO":false,
          "FAE_PAM_TASA_CAMBIO":1.0000,
          "FAE_PAM_TASA_CAMBIO_OPERACION":"*",
          "FAE_PAM_SIMBOLO_MONEDA":"US$",
          "FAE_PAM_NOMBRE_MONEDA":"DOLARES AMERICANOS",
          "FAE_PAM_CODIGO":0,
          "FAE_ING_NUMFAC":"0",
          "FAE_ING_NUMPED":"0025344",
          "FAE_CONDICION_PAGO":"CREDITO",
          "FAE_MANUAL":false,
          "FAE_NUMDOC":4201,
          "FAE_CODNVL":3,
          "FAE_CODBOD":"B1   ",
          "FAE_UNOPORCIENTO":false,
          "FAE_EXENTO":true,
          "FAE_FECHAPAGO":"2022-04-24T00:00:00",
          "FAE_GRAN_TOTAL":243.930000,
          "FAE_TOTAL_RETENCION":0.000000,
          "FAE_SUB_TOTAL":243.930000,
          "FAE_TOTAL_IMPUESTO":0.000000,
          "FAE_SUB_TOTAL_CON_DESCUENTO":243.930000,
          "FAE_TOTAL_SOLO_DESCUENTO":0.000000,
          "FAE_TOTAL_GRAVADO":0.000000,
          "FAE_TOTAL_EXENTO":243.930000,
          "FAE_CODREG":0,
          "FAE_REGION":"",
          "FAE_CODZON":0,
          "FAE_ZONA":"",
          "FAE_SUCURSAL":"SUC. ESCALON",
          "FAE_CODDIS":0,
          "FAE_DISTRITO":"",
          "FAE_CODTPR":0,
          "FAE_TIPO_RUTA":"",
          "FAE_CODRUT":"",
          "FAE_RUTA":"",
          "FAE_CODVEN_RUTA":"",
          "FAE_VENDEDOR_RUTA":"",
          "FAE_CODPAI_CLIENTE":1,
          "FAE_PAIS_CLIENTE":"EL SALVADOR",
          "FAE_CODDEP_CLIENTE":20,
          "FAE_DEPTO_CLIENTE":"LA LIBERTAD",
          "FAE_CODMUN_CLIENTE":355,
          "FAE_MUNICIPIO_CLIENTE":"SAN JUAN OPICO",
          "FAE_TRANSACCION":"00020",
          "FAE_CODVEN_CLIENTE":"VOFIC",
          "FAE_VENDEDOR_CLIENTE":"IOSIF RICARDO NAJARRO",
          "FAE_FECHA_TRANSACCION":"2022-03-25T12:27:13.060",
          "FAE_COMENTARIOS":"",
          "FAE_IDPDE":0,
          "FAE_FACTURA_DIRECCION":"",
          "FAE_CANT_LETRAS":"DOSCIENTOS CUARENTA Y TRES CON 93_100",
          "FAE_FAC_INTERNA":false,
          "FAE_FAC_CODCCO":0,
          "FAE_CREDITO_CXC":true,
          "FAE_ESTADO":"IMPRESA",
          "FAE_LOG_ENVIO":"",
          "FAE_HINT":"",
          "FAE_DESCRIPTION":"",
          "FAE_DATA":"",
          "FAE_XML":"",
          "FAE_PENDIENTE_SAT":true,
          "FAE_DOCUMENTGUID":"",
          "FAE_TRANSACCION_INV":"00041",
          "FAE_DESPACHO_PENDIENTE":false,
          "FAE_CODCNR":"",
          "FAE_CANAL":"",
          "FAE_MODUL":"LIN",
          "FAE_ROTATIVO":"N",
          "FAE_NUMEROACCESO":""
       }
    ]
 }